# Generated by Django 3.1.2 on 2020-11-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
