# Generated by Django 3.1.2 on 2020-11-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='t_project',
        ),
    ]
